import fs from 'node:fs/promises'
import path from 'node:path'
import pc from 'picocolors'
import { RushCMSClient } from '@rushcms/client'
import type { Collection, CollectionField } from '@rushcms/types'
import { loadConfig } from '../utils/config-loader'

interface CodegenOptions {
	out: string
}

const fieldTypeMap: Record<string, string> = {
	'content-editor': 'TipTapContent',
	'markdown': 'string',
	'text': 'string',
	'textarea': 'string',
	'image': 'string',
	'gallery': 'GalleryImage[]',
	'list': 'string[]'
}

function toTypeName(slug: string): string {
	return slug
		.split(/[-_]/)
		.map(part => part.charAt(0).toUpperCase() + part.slice(1))
		.join('') + 'Entry'
}

function getFieldType(field: CollectionField): string {
	return fieldTypeMap[field.type] || 'unknown'
}

function extractFields(collection: Collection): CollectionField[] {
	if (!collection.options) return []

	const fields: CollectionField[] = []

	for (const section of collection.options.main || []) {
		for (const field of section.fields || []) {
			fields.push(field)
		}
	}

	for (const section of collection.options.sidebar || []) {
		for (const field of section.fields || []) {
			fields.push(field)
		}
	}

	return fields
}

function generateInterface(collection: Collection): string {
	const typeName = toTypeName(collection.slug)
	const fields = extractFields(collection)

	if (fields.length === 0) {
		return `export interface ${typeName} {\n\t[key: string]: unknown\n}`
	}

	const lines = fields.map(field => {
		const name = field.data.config.name
		const tsType = getFieldType(field)
		const required = field.data.validation?.required
		const optional = required ? '' : '?'
		return `\t${name}${optional}: ${tsType}`
	})

	return `export interface ${typeName} {\n${lines.join('\n')}\n}`
}

export async function codegen(options: CodegenOptions) {
	console.log(pc.cyan('RushCMS Codegen'))
	console.log(pc.gray('Loading configuration...'))

	const config = await loadConfig()
	const client = new RushCMSClient({
		baseUrl: config.apiUrl,
		apiToken: config.apiToken,
		siteSlug: config.siteSlug,
		cache: { enabled: false }
	})

	console.log(pc.gray(`Fetching collections from ${config.siteSlug}...`))

	const response = await client.getCollections()
	const collections = response.data || []

	if (collections.length === 0) {
		console.log(pc.yellow('No collections found.'))
		return
	}

	console.log(pc.gray(`Found ${collections.length} collection(s): ${collections.map((c: Collection) => c.slug).join(', ')}`))

	const needsTipTap = collections.some((c: Collection) =>
		extractFields(c).some(f => f.type === 'content-editor')
	)
	const needsGallery = collections.some((c: Collection) =>
		extractFields(c).some(f => f.type === 'gallery')
	)

	const imports: string[] = []
	if (needsTipTap) imports.push('TipTapContent')
	if (needsGallery) imports.push('GalleryImage')

	const parts: string[] = [
		'// Generated by @rushcms/cli — do not edit manually',
		''
	]

	if (imports.length > 0) {
		parts.push(`import type { ${imports.join(', ')} } from '@rushcms/types'`)
		parts.push('')
	}

	for (const collection of collections) {
		parts.push(generateInterface(collection as Collection))
		parts.push('')
	}

	const collectionMap = collections
		.map((c: Collection) => `\t${c.slug}: ${toTypeName(c.slug)}`)
		.join('\n')

	parts.push(`export interface RushCMSCollections {\n${collectionMap}\n}`)
	parts.push('')

	const content = parts.join('\n')
	const outputPath = path.resolve(process.cwd(), options.out)

	await fs.mkdir(path.dirname(outputPath), { recursive: true })
	await fs.writeFile(outputPath, content)

	console.log(pc.green(`\u2714 Types generated at ${options.out}`))
}
