import fs from 'fs/promises'
import path from 'path'
import pc from 'picocolors'

interface CodegenOptions {
    out: string
}

export async function codegen(options: CodegenOptions) {
    console.log(pc.cyan('RushCMS Codegen'))
    console.log(pc.gray('Generating types...'))

    // TODO: Load config from rushcms.config.js
    // TODO: Fetch schema from API

    const mockSchema = {
        'custom_hero': {
            type: 'block',
            fields: {
                title: 'string',
                image: 'FeaturedImage'
            }
        },
        'custom_cta': {
            type: 'block',
            fields: {
                link: 'string',
                label: 'string'
            }
        }
    }

    const content = `
// Generated by @rushcms/cli
import '@rushcms/types'

declare module '@rushcms/types' {
  export interface CustomBlockMap {
    'custom_hero': { title: string; image: FeaturedImage };
    'custom_cta': { link: string; label: string };
  }
}
`

    const outputPath = path.resolve(process.cwd(), options.out)
    await fs.writeFile(outputPath, content.trim())

    console.log(pc.green(`✔ Types generated at ${options.out}`))
}
